apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: {{.Values.streamlit.replicas}}
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: {{.Values.streamlit.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.streamlit.port}}
        env:
        - name: RAY_ADDRESS
          value: {{.Values.streamlit.rayURI}}
        - name: NEO4J_URI
          value: {{.Values.streamlit.neo4jURI}}
        - name: NEO4J_USERNAME
          value: {{.Values.streamlit.neo4jUSERNAME}}
        - name: NEO4J_PASSWORD
          value: {{.Values.streamlit.neo4jPASSWORD}}
