apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 82
      targetPort: {{.Values.streamlit.port}}
  type: LoadBalancer # Change to ClusterIP if using an Ingress