apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: {{.Values.ray.name}}
spec:
  rayVersion: {{.Values.ray.rayVersion}}
  headGroupSpec:
    headService:
      metadata:
        name: ray-head-service
      spec:
        ports:
          - protocol: TCP
            port: 80
        type: LoadBalancer # Change to ClusterIP if using an Ingress
    rayStartParams:
      dashboard-host: {{.Values.ray.dashboardHost}}
    template:
      spec:
        containers:
          - name: ray-head
            image: {{.Values.ray.image}}
            imagePullPolicy: Always
            resources:
              limits: {cpu: {{.Values.ray.head.resources.cpu}}, memory: {{.Values.ray.head.resources.memory}}}
  workerGroupSpecs:
  - replicas: {{.Values.ray.worker.replicas}}
    minReplicas: {{.Values.ray.worker.minReplicas}}
    maxReplicas: {{.Values.ray.worker.maxReplicas}}
    groupName: default-group
    rayStartParams: {}
    template:
      spec:
        containers:
          - name: ray-worker
            image: {{.Values.ray.image}}
            imagePullPolicy: Always
            resources:
              limits: {cpu: {{.Values.ray.worker.resources.cpu}}, memory: {{.Values.ray.worker.resources.memory}}}
