apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: {{.Values.ray.name}}
spec:
  rayVersion: {{.Values.ray.rayVersion}}
  headGroupSpec:
    rayStartParams:
      dashboard-host: {{.Values.ray.dashboardHost}}
    template:
      spec:
        containers:
          - name: ray-head
            image: {{.Values.ray.image}}
            imagePullPolicy: Always
            resources:
              limits: {{.Values.ray.head.resources.limits}}
  workerGroupSpecs:
  - replicas: {{.Values.ray.worker.replicas}}
    minReplicas: {{.Values.ray.worker.minReplicas}}
    maxReplicas: {{.Values.ray.worker.maxReplicas}}
    groupName: default-group
    rayStartParams: {}
    template:
      spec:
        containers:
          - name: ray-worker
            image: {{.Values.ray.image}}
            imagePullPolicy: Always
            resources:
              limits: {{.Values.ray.worker.resources.limits}}
