apiVersion: apps/v1
kind: Deployment
metadata:
  name: neodash
  labels:
    app: neodash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neodash
  template:
    metadata:
      labels:
        app: neodash
    spec:
      containers:
      - name: neodash
        image: nielsdejong/neodash:latest
        ports:
        - containerPort: 5005
        # Optional: Set environment variables for Standalone/Reader mode
        env:
        - name: neodash_standalone
          value: "false" # Set to "true" for read-only mode
---
apiVersion: v1
kind: Service
metadata:
  name: neodash-service
spec:
  selector:
    app: neodash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
  type: LoadBalancer # Change to ClusterIP if using an Ingress
