apiVersion: apps/v1
kind: Deployment
metadata:
  name: neodash
  labels:
    app: neodash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neodash
  template:
    metadata:
      labels:
        app: neodash
    spec:
      containers:
      - name: neodash
        image: {{.Values.neodash.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
        - name: neodash_standalone
          value: "false" # Set to "true" for read-only mode
