ray:

neodash:


streamlit:
  port: 8501

# values.yaml
neo4j:
  neo4j:
    # Mandatory: The internal name for the Neo4j instance
    name: "parish-records-kg"
    # Select edition: "community" (default) or "enterprise"
    edition: "community"
    # Accept the license if using Enterprise edition
    acceptLicenseAgreement: "no"


neodash:
  neo4j:
    url: "neo4j://my-neo4j-service:7687"