ray:
  name: raycluster
  image: ghcr.io/therrypeople/archive_entities/ray:latest

streamlit:
  image: ghcr.io/therrypeople/archive_entities/streamlit:latest
  port: 8501
  rayURI: raycluster-head-svc.default.svc.cluster.local:10001
  neo4jURI: archive-entities.default.svc.cluster.local
  neo4jPASSWORD: neo4j
  neo4jUSERNAME: neo4j

neo4j:
  neo4j:
    # Mandatory: The internal name for the Neo4j instance
    name: "parish-records-kg"
    # Select edition: "community" (default) or "enterprise"
    edition: "community"
    password: neo4j
  volumes:
    data:
      mode: defaultStorageClass


neodash:
  neo4j:
    url: "neo4j://archive-entities.default.svc.cluster.local:7687"